### ISSUE TITLE
Create tool to convert Million Song data to our database format

### ISSUE THREAD

**Issue by tylerchr** [tylerchr/parallel-database#1]
Here is the million song thing:

http://labrosa.ee.columbia.edu/millionsong/pages/example-track-description

**Comment by tdecker91** [comment]
I converted the 1 million song file using the generator tool. Even after changes to the way the hasher worked it was still incredibly slow on my laptop. But it was able to finish in like 2 minutes on my desktop. The resulting data.db file is 1GB so I recommend generating rather than hosting it something for us to download.

**Comment by tdecker91** [comment]
Here's a link to the full database file https://www.dropbox.com/s/gyto9l22u01978l/data.db?dl=0
